Rearrange action workflow logic

diff --git a/.github/workflows/ubuntu-builder.yml b/.github/workflows/ubuntu-builder.yml
--- a/.github/workflows/ubuntu-builder.yml
+++ b/.github/workflows/ubuntu-builder.yml
@@ -7,13 +7,18 @@ on:
       _cpusched:
         required: true
         type: string
+      database:
+        required: false
+        type: string
 
   workflow_dispatch: # on button click
       inputs:
       _cpusched:
         required: true
         type: string
-
+      database:
+        required: false
+        type: string
 
 env:
   _waydroid: "true"
@@ -69,3 +74,79 @@ jobs:
           path: |
             ${{ github.workspace }}/DEBS/*.deb
             ${{ github.workspace }}/kernelconfig*.txt
+
+  build-database:
+    env:
+      ubuntu_repo_dir: "debian/main/x86_64"
+      ubuntu_packages_file: "debian/main/x86_64/Packages"
+      ubuntu_release_file: "debian/main/x86_64/Release"
+      ubuntu_inrelease_file: "debian/main/x86_64/InRelease"
+    
+    if: inputs.database == 'true'
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Install dependencies
+        run: sudo apt-get install -y dpkg-dev gpg
+
+      - name: Checkount linux-tkg-repo
+        uses: actions/checkout@v4.1.1
+
+      # (Temporaly disable ubuntu repo signing)
+      #- name: Import GPG key
+      #  uses: crazy-max/ghaction-import-gpg@v6
+      #  with:
+      #    gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
+      #    passphrase: ${{ secrets.PASSPHRASE }}
+
+      - name: Update package list database
+        run: |
+          # Generate the Packages file
+          dpkg-scanpackages "./${{ env.ubuntu_repo_dir }}" /dev/null > "./${{ env.ubuntu_packages_file }}" || {
+            echo "Error generating Packages file!" >&2
+            exit 1
+          }
+          gzip -k -f -9 "./${{ env.ubuntu_packages_file }}" || {
+            echo "Error compressing Packages file!" >&2
+            exit 1
+          }
+        
+          # Generate the Release file
+          # Optional configuration information
+          cp ./.github/distributions "./${{ env.ubuntu_release_file }}" && \
+          echo -e "Date: $(LANG=C date -Ru)" >> "./${{ env.ubuntu_release_file }}" || {
+            echo "Warning: There is no `distributions` file" >&2
+          }
+        
+          # Calculate and add checksums
+          calculate_checksums() {
+            local checksum_type="$1"
+            local checksum_file="$2"
+            local checksum=$("$checksum_type" "$checksum_file" | cut -d' ' -f1)
+            local file_size=$(wc -c "$checksum_file" | cut -d' ' -f1)
+            printf " %s %16d %s\n" "$checksum" "$file_size" "$checksum_file" >> "./${{ env.ubuntu_release_file }}"
+          }
+        
+          calculate_checksums "md5sum" "./${{ env.ubuntu_packages_file }}.gz"
+          calculate_checksums "md5sum" "./${{ env.ubuntu_packages_file }}"
+          calculate_checksums "sha256sum" "./${{ env.ubuntu_packages_file }}.gz"
+          calculate_checksums "sha256sum" "./${{ env.ubuntu_packages_file }}"
+
+          # (Temporaly disable ubuntu repo signing)
+          ## Clearsign the Release file
+          #rm -f ${{ env.ubuntu_inrelease_file }}
+          #gpg --batch --clearsign --digest-algo SHA512 -o "${{ env.ubuntu_inrelease_file }}" "${{ env.ubuntu_release_file }}" || {
+          #  echo "Error signing Release file!" >&2
+          #}
+
+      - name: Pre commit setup
+        run: git config --global --add safe.directory /__w/linux-tkg-repo/linux-tkg-repo
+        
+      - name: Commit updated package list database
+        run: |
+          git config user.name github-actions
+          git config user.email github-actions@github.com
+          git add .
+          git commit -m "Push updated package list database"
+          git pull --rebase
+          git push
